In [ ]:
import itertools
import numpy as np
import codecs

In [ ]:
x=[]
for v in itertools.product(['A', 'T', 'G','C'], repeat=9):x.append("".join(list(map(str,v))))

IOPub data rate exceeded.
The notebook server will temporarily stop sending output
to the client in order to avoid crashing it.
To change this limit, set the config variable
`--NotebookApp.iopub_data_rate_limit`.

Current values:
NotebookApp.iopub_data_rate_limit=1000000.0 (bytes/sec)
NotebookApp.rate_limit_window=3.0 (secs)



In [ ]:
x

['AAAAAAAAA',
 'AAAAAAAAT',
 'AAAAAAAAG',
 'AAAAAAAAC',
 'AAAAAAATA',
 'AAAAAAATT',
 'AAAAAAATG',
 'AAAAAAATC',
 'AAAAAAAGA',
 'AAAAAAAGT',
 'AAAAAAAGG',
 'AAAAAAAGC',
 'AAAAAAACA',
 'AAAAAAACT',
 'AAAAAAACG',
 'AAAAAAACC',
 'AAAAAATAA',
 'AAAAAATAT',
 'AAAAAATAG',
 'AAAAAATAC',
 'AAAAAATTA',
 'AAAAAATTT',
 'AAAAAATTG',
 'AAAAAATTC',
 'AAAAAATGA',
 'AAAAAATGT',
 'AAAAAATGG',
 'AAAAAATGC',
 'AAAAAATCA',
 'AAAAAATCT',
 'AAAAAATCG',
 'AAAAAATCC',
 'AAAAAAGAA',
 'AAAAAAGAT',
 'AAAAAAGAG',
 'AAAAAAGAC',
 'AAAAAAGTA',
 'AAAAAAGTT',
 'AAAAAAGTG',
 'AAAAAAGTC',
 'AAAAAAGGA',
 'AAAAAAGGT',
 'AAAAAAGGG',
 'AAAAAAGGC',
 'AAAAAAGCA',
 'AAAAAAGCT',
 'AAAAAAGCG',
 'AAAAAAGCC',
 'AAAAAACAA',
 'AAAAAACAT',
 'AAAAAACAG',
 'AAAAAACAC',
 'AAAAAACTA',
 'AAAAAACTT',
 'AAAAAACTG',
 'AAAAAACTC',
 'AAAAAACGA',
 'AAAAAACGT',
 'AAAAAACGG',
 'AAAAAACGC',
 'AAAAAACCA',
 'AAAAAACCT',
 'AAAAAACCG',
 'AAAAAACCC',
 'AAAAATAAA',
 'AAAAATAAT',
 'AAAAATAAG',
 'AAAAATAAC',
 'AAAAATATA',
 'AAAAATATT',
 'AAAAATATG',
 'AAAA

In [ ]:
A=[]
T=[]
G=[]
C=[]
for j in range(len(x[0])):
    A.append([i[j] for i in x].count('A'))
    T.append([i[j] for i in x].count('T'))
    G.append([i[j] for i in x].count('G'))
    C.append([i[j] for i in x].count('C'))
print ("A", A)
print ("T", T)
print ("G", G)
print ("C", C)

A [65536, 65536, 65536, 65536, 65536, 65536, 65536, 65536, 65536]
T [65536, 65536, 65536, 65536, 65536, 65536, 65536, 65536, 65536]
G [65536, 65536, 65536, 65536, 65536, 65536, 65536, 65536, 65536]
C [65536, 65536, 65536, 65536, 65536, 65536, 65536, 65536, 65536]


In [ ]:
n = [A,T,G,C]
n = np.array(n)
print(n)
percentages = n/n.sum(axis=0) * 100
print(percentages)

[[65536 65536 65536 65536 65536 65536 65536 65536 65536]
 [65536 65536 65536 65536 65536 65536 65536 65536 65536]
 [65536 65536 65536 65536 65536 65536 65536 65536 65536]
 [65536 65536 65536 65536 65536 65536 65536 65536 65536]]
[[25. 25. 25. 25. 25. 25. 25. 25. 25.]
 [25. 25. 25. 25. 25. 25. 25. 25. 25.]
 [25. 25. 25. 25. 25. 25. 25. 25. 25.]
 [25. 25. 25. 25. 25. 25. 25. 25. 25.]]


In [ ]:
html ="""<html><table border="1">
<tr><th>Bases</th><th>1</th><th>2</th><th>3</th><th>4</th><th>5</th><th>6</th><th>7</th><th>8</th><th>9</th></tr>
<tr><th>A</th><td>65536</td><td>65536</td><td>65536</td><td>65536</td><td>65536</td><td>65536</td><td>65536</td><td>65536</td><td>65536</td></tr>
<tr><th>T</th><td>65536</td><td>65536</td><td>65536</td><td>65536</td><td>65536</td><td>65536</td><td>65536</td><td>65536</td><td>65536</td></tr>
<tr><th>G</th><td>65536</td><td>65536</td><td>65536</td><td>65536</td><td>65536</td><td>65536</td><td>65536</td><td>65536</td><td>65536</td></tr>
<tr><th>C</th><td>65536</td><td>65536</td><td>65536</td><td>65536</td><td>65536</td><td>65536</td><td>65536</td><td>65536</td><td>65536</td></tr>
<tr><th>%A</th><td>25%</td><td>25%</td><td>25%</td><td>25%</td><td>25%</td><td>25%</td><td>25%</td><td>25%</td><td>25%</td></tr>
<tr><th>%T</th><td>25%</td><td>25%</td><td>25%</td><td>25%</td><td>25%</td><td>25%</td><td>25%</td><td>25%</td><td>25%</td></tr>
<tr><th>%G</th><td>25%</td><td>25%</td><td>25%</td><td>25%</td><td>25%</td><td>25%</td><td>25%</td><td>25%</td><td>25%</td></tr>
<tr><th>%C</th><td>25%</td><td>25%</td><td>25%</td><td>25%</td><td>25%</td><td>25%</td><td>25%</td><td>25%</td><td>25%</td></tr>
</table></html>"""

f=open('Count.html','w')
f.write(html)
f.close()

file = codecs.open("Count.html", 'r', "utf-8")
  
# using .read method to view the html 
# code from our object
print(file.read())

<html><table border="1">
<tr><th>Bases</th><th>1</th><th>2</th><th>3</th><th>4</th><th>5</th><th>6</th><th>7</th><th>8</th><th>9</th></tr>
<tr><th>A</th><td>65536</td><td>65536</td><td>65536</td><td>65536</td><td>65536</td><td>65536</td><td>65536</td><td>65536</td><td>65536</td></tr>
<tr><th>T</th><td>65536</td><td>65536</td><td>65536</td><td>65536</td><td>65536</td><td>65536</td><td>65536</td><td>65536</td><td>65536</td></tr>
<tr><th>G</th><td>65536</td><td>65536</td><td>65536</td><td>65536</td><td>65536</td><td>65536</td><td>65536</td><td>65536</td><td>65536</td></tr>
<tr><th>C</th><td>65536</td><td>65536</td><td>65536</td><td>65536</td><td>65536</td><td>65536</td><td>65536</td><td>65536</td><td>65536</td></tr>
<tr><th>%A</th><td>25%</td><td>25%</td><td>25%</td><td>25%</td><td>25%</td><td>25%</td><td>25%</td><td>25%</td><td>25%</td></tr>
<tr><th>%T</th><td>25%</td><td>25%</td><td>25%</td><td>25%</td><td>25%</td><td>25%</td><td>25%</td><td>25%</td><td>25%</td></tr>
<tr><th>%G</th><td>